### ISSUE TITLE
Suggested improvement to the 'Uninstall' parameter

### ISSUE THREAD

**Issue by amirsc3** [microsoft/mdefordownlevelserver#25] opened 2022-11-14 11:17 UTC
The -uninstall parameter should check if SENSE service is running and if it is NOT running it should automatically change the following keys before attempting to uninstall the MSI:
reg add "HKLM\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status" /v OnboardingState /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Services\Sense" /v Start /t REG_DWORD /d 4 /f

Otherwise, the MSI fails to install asking to offboard even though offboarding has already run and SENSE is stopped.

**Comment by tcoserea-msft** [comment] 2023-04-13 01:54
These things should be performed by Sense service during offboarding. By design, only Sense service is allowed to update these registry keys and not install.ps1 even when run as Administrator. 

We had a bug, introduced around Aug 2022 and currently fixed, that prevented Sense to do these things for Downlevel servers during offboarding. Just make sure Windows Defender is up to date (the bug was introduced and also fixed via signature updates) before running offboarding script or "Install.ps1 -Uninstall -OffboardingScript ..."

**Closed by tcoserea-msft** 2023-04-13 01:54 UTC
